version = "1.0"

[metadata]
author_name = "LoCoBench-Agent Adapter"
author_email = "unknown"
difficulty = "expert"
category = "architectural_understanding"
tags = [ "locobench-agent", "architectural_understanding", "go",]
language = "go"
context_length = 841973
files_count = 80
task_id = "go_ml_nlp_expert_053_architectural_understanding_expert_01"

[verifier]
timeout_sec = 600.0

[agent]
timeout_sec = 1200.0

[environment]
build_timeout_sec = 300.0
cpus = 2
memory_mb = 8192
storage_mb = 20480
gpus = 0

[verifier.env]
