[metadata]
name = "sgt-025"
description = "Revert part of https://github.com/pytorch/pytorch/pull/161916 to continue building CUDA 12.9 nightly"
license = "MIT"

[task]
id = "sgt-025"
repo = "pytorch"
category = "cross_module_bug_fix"
language = "cpp"
difficulty = "hard"
time_limit_sec = 600

[verification]
type = "test"
command = "make test"
