version = "1.0"

[metadata]
author_name = "DI-Bench"
author_email = "unknown"
difficulty = "medium"
category = "dependency-inference"
tags = [ "dibench", "python", "dependency-inference",]
language = "python"
instance_id = "MartinThoma_flake8-simplify"

[verifier]
timeout_sec = 1200.0

[agent]
timeout_sec = 1000.0

[environment]
build_timeout_sec = 1800.0
cpus = 2
memory_mb = 4096
storage_mb = 10240
