version = "1.0"

[metadata]
author_name = "LoCoBench-Agent Adapter"
author_email = "unknown"
difficulty = "expert"
category = "bug_investigation"
tags = [ "locobench-agent", "bug_investigation", "csharp",]
language = "csharp"
context_length = 1113221
files_count = 84
task_id = "csharp_data_warehouse_expert_012_bug_investigation_expert_01"

[verifier]
timeout_sec = 600.0

[agent]
timeout_sec = 1200.0

[environment]
build_timeout_sec = 300.0
cpus = 2
memory_mb = 8192
storage_mb = 20480
gpus = 0

[verifier.env]
