[metadata]
name = "sgt-008"
description = "Same as https://github.com/pytorch/pytorch/pull/162493\r"
license = "MIT"

[task]
id = "sgt-008"
repo = "pytorch"
category = "cross_module_bug_fix"
language = "cpp"
difficulty = "hard"
time_limit_sec = 600

[verification]
type = "test"
command = "make test"
