version = "1.0"
[metadata]
name = "sgt-020"
description = "Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):"
license = "MIT"

[task]
id = "sgt-020"
repo = "pytorch"
category = "cross_module_bug_fix"
language = "cpp"
difficulty = "easy"
time_limit_sec = 600

[verification]
type = "test"
command = "make test"
