version = "1.0"
[metadata]
name = "sgt-023"
description = "Stack from [ghstack](https://github.com/ezyang/ghstack/tree/0.12.0) (oldest at bottom):"
license = "MIT"

[task]
id = "sgt-023"
repo = "pytorch"
category = "feature_implementation"
language = "cpp"
difficulty = "easy"
time_limit_sec = 600

[verification]
type = "test"
command = "make test"
