version = "1.0"
[metadata]
name = "sgt-022"
description = "Stack from [ghstack](https://github.com/ezyang/ghstack/tree/0.12.0) (oldest at bottom):\r"
license = "MIT"

[task]
id = "sgt-022"
repo = "pytorch"
category = "cross_module_bug_fix"
language = "cpp"
difficulty = "easy"
time_limit_sec = 600

[verification]
type = "test"
command = "make test"
