version = "1.0"
[metadata]
name = "sgt-019"
description = "Fixes https://github.com/pytorch/pytorch/issues/156377\r"
license = "MIT"

[task]
id = "sgt-019"
repo = "pytorch"
category = "cross_module_bug_fix"
language = "cpp"
difficulty = "medium"
time_limit_sec = 600

[verification]
type = "test"
command = "make test"
