services:
  main:
    build:
      context: ${CONTEXT_DIR}
    image: ${MAIN_IMAGE_NAME}
    command: [ "sh", "-c", "sleep infinity" ]
    network_mode: ${NETWORK_MODE:-bridge}
    environment:
      - TEST_DIR=${TEST_DIR}
      - SWEBENCH_REPO_COMMIT=locobench-rust_ml_computer_vision_expert_054--main
      - LOCOBENCH_GITHUB_ORG=sg-benchmarks
      - LOCOBENCH_PROJECT_ID=rust_ml_computer_vision_expert_054
    volumes:
      - ${HOST_VERIFIER_LOGS_PATH}:${ENV_VERIFIER_LOGS_PATH}
      - ${HOST_AGENT_LOGS_PATH}:${ENV_AGENT_LOGS_PATH}
      - ${CONTEXT_DIR}/../tests:/tests
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
