version = "1.0"

[metadata]
author_name = "LoCoBench-Agent Adapter"
author_email = "unknown"
difficulty = "expert"
category = "architectural_understanding"
tags = [ "locobench-agent", "architectural_understanding", "c",]
language = "c"
context_length = 946983
files_count = 77
task_id = "c_ml_nlp_expert_017_architectural_understanding_expert_01"

[verifier]
timeout_sec = 600.0

[agent]
timeout_sec = 1200.0

[environment]
build_timeout_sec = 300.0
cpus = 2
memory_mb = 8192
storage_mb = 20480
gpus = 0

[verifier.env]
