version = "1.0"

[metadata]
author_name = "LoCoBench-Agent Adapter"
author_email = "unknown"
difficulty = "expert"
category = "cross_file_refactoring"
tags = [ "locobench-agent", "cross_file_refactoring", "cpp",]
language = "cpp"
context_length = 975132
files_count = 79
task_id = "cpp_web_blog_expert_040_cross_file_refactoring_expert_01"

[verifier]
timeout_sec = 600.0

[agent]
timeout_sec = 1200.0

[environment]
build_timeout_sec = 300.0
cpus = 2
memory_mb = 8192
storage_mb = 20480
gpus = 0

[verifier.env]
